/*
 * online bakery microservice
 * Micro service to online bakery
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.mikrobrama.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * Bread
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-23T15:31:47.012026+01:00[Europe/Warsaw]")
public class Bread {
  @JsonProperty("breadType")
  private String breadType = null;

  @JsonProperty("glutenFree")
  private Boolean glutenFree = null;

  @JsonProperty("name")
  private Boolean name = null;

  public Bread breadType(String breadType) {
    this.breadType = breadType;
    return this;
  }

   /**
   * Get breadType
   * @return breadType
  **/
  public String getBreadType() {
    return breadType;
  }

  public void setBreadType(String breadType) {
    this.breadType = breadType;
  }

  public Bread getGlutenFree(Boolean glutenFree) {
    this.glutenFree = glutenFree;
    return this;
  }

   /**
   * Get isGlutenFree
   * @return isGlutenFree
  **/
  public Boolean getGlutenFree() {
    return glutenFree;
  }

  public void setGlutenFree(Boolean glutenFree) {
    this.glutenFree = glutenFree;
  }

  public Bread name(Boolean name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public Boolean isName() {
    return name;
  }

  public void setName(Boolean name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Bread bread = (Bread) o;
    return Objects.equals(this.breadType, bread.breadType) &&
        Objects.equals(this.glutenFree, bread.glutenFree) &&
        Objects.equals(this.name, bread.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(breadType, glutenFree, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Bread {\n");
    
    sb.append("    breadType: ").append(toIndentedString(breadType)).append("\n");
    sb.append("    isGlutenFree: ").append(toIndentedString(glutenFree)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
