/*
 * online bakery microservice
 * Micro service to online bakery
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.mikrobrama.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * Cake
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-23T15:31:47.012026+01:00[Europe/Warsaw]")
public class Cake {
  @JsonProperty("cakeType")
  private String cakeType = null;

  @JsonProperty("isVegan")
  private Boolean isVegan = null;

  @JsonProperty("birthdayName")
  private String birthdayName = null;

  public Cake cakeType(String cakeType) {
    this.cakeType = cakeType;
    return this;
  }

   /**
   * Get cakeType
   * @return cakeType
  **/
  public String getCakeType() {
    return cakeType;
  }

  public void setCakeType(String cakeType) {
    this.cakeType = cakeType;
  }

  public Cake isVegan(Boolean isVegan) {
    this.isVegan = isVegan;
    return this;
  }

   /**
   * Get isVegan
   * @return isVegan
  **/
  public Boolean isIsVegan() {
    return isVegan;
  }

  public void setIsVegan(Boolean isVegan) {
    this.isVegan = isVegan;
  }

  public Cake birthdayName(String birthdayName) {
    this.birthdayName = birthdayName;
    return this;
  }

   /**
   * Get birthdayName
   * @return birthdayName
  **/
  public String getBirthdayName() {
    return birthdayName;
  }

  public void setBirthdayName(String birthdayName) {
    this.birthdayName = birthdayName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Cake cake = (Cake) o;
    return Objects.equals(this.cakeType, cake.cakeType) &&
        Objects.equals(this.isVegan, cake.isVegan) &&
        Objects.equals(this.birthdayName, cake.birthdayName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cakeType, isVegan, birthdayName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Cake {\n");
    
    sb.append("    cakeType: ").append(toIndentedString(cakeType)).append("\n");
    sb.append("    isVegan: ").append(toIndentedString(isVegan)).append("\n");
    sb.append("    birthdayName: ").append(toIndentedString(birthdayName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
