/*
 * online bakery microservice
 * Micro service to online bakery
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.mikrobrama.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import org.bp.mikrobrama.model.DeliveryPlace;
/**
 * DeliveryRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-29T17:08:55.309591100+01:00[Europe/Warsaw]")
public class DeliveryRequest {
  @JsonProperty("orderId")
  private String orderId = null;

  @JsonProperty("deliveryPlace")
  private DeliveryPlace deliveryPlace = null;

  public DeliveryRequest orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public DeliveryRequest deliveryPlace(DeliveryPlace deliveryPlace) {
    this.deliveryPlace = deliveryPlace;
    return this;
  }

   /**
   * Get deliveryPlace
   * @return deliveryPlace
  **/
  public DeliveryPlace getDeliveryPlace() {
    return deliveryPlace;
  }

  public void setDeliveryPlace(DeliveryPlace deliveryPlace) {
    this.deliveryPlace = deliveryPlace;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeliveryRequest deliveryRequest = (DeliveryRequest) o;
    return Objects.equals(this.orderId, deliveryRequest.orderId) &&
        Objects.equals(this.deliveryPlace, deliveryRequest.deliveryPlace);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderId, deliveryPlace);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeliveryRequest {\n");
    
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    deliveryPlace: ").append(toIndentedString(deliveryPlace)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
