/*
 * online bakery microservice
 * Micro service to online bakery
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.mikrobrama.model;

import java.util.Objects;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import org.bp.types.DeliveryPlace;
import org.joda.time.*;
/**
 * DeliveryResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-29T17:08:55.309591100+01:00[Europe/Warsaw]")
public class DeliveryResponse {
  @JsonProperty("deliveryPlace")
  private DeliveryPlace deliveryPlace = null;

  @JsonProperty("deliveryId")
  private String deliveryId = null;

  @JsonProperty("orderId")
  private String orderId = null;

  @JsonProperty("deliveryDate")
  private OffsetDateTime deliveryDate = null;

  public DeliveryResponse deliveryPlace(DeliveryPlace deliveryPlace) {
    this.deliveryPlace = deliveryPlace;
    return this;
  }

   /**
   * Get deliveryPlace
   * @return deliveryPlace
  **/
  public DeliveryPlace getDeliveryPlace() {
    return deliveryPlace;
  }

  public void setDeliveryPlace(DeliveryPlace deliveryPlace) {
    this.deliveryPlace = deliveryPlace;
  }

  public DeliveryResponse deliveryId(String deliveryId) {
    this.deliveryId = deliveryId;
    return this;
  }

   /**
   * Get deliveryId
   * @return deliveryId
  **/
  public String getDeliveryId() {
    return deliveryId;
  }

  public void setDeliveryId(String deliveryId) {
    this.deliveryId = deliveryId;
  }

  public DeliveryResponse orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public DeliveryResponse deliveryDate(OffsetDateTime deliveryDate) {
    this.deliveryDate = deliveryDate;
    return this;
  }

   /**
   * Get deliveryDate
   * @return deliveryDate
  **/
  public OffsetDateTime getDeliveryDate() {
    return deliveryDate;
  }

  public void setDeliveryDate(OffsetDateTime deliveryDate) {
    this.deliveryDate = deliveryDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeliveryResponse deliveryResponse = (DeliveryResponse) o;
    return Objects.equals(this.deliveryPlace, deliveryResponse.deliveryPlace) &&
        Objects.equals(this.deliveryId, deliveryResponse.deliveryId) &&
        Objects.equals(this.orderId, deliveryResponse.orderId) &&
        Objects.equals(this.deliveryDate, deliveryResponse.deliveryDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveryPlace, deliveryId, orderId, deliveryDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeliveryResponse {\n");
    
    sb.append("    deliveryPlace: ").append(toIndentedString(deliveryPlace)).append("\n");
    sb.append("    deliveryId: ").append(toIndentedString(deliveryId)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    deliveryDate: ").append(toIndentedString(deliveryDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
