/*
 * online bakery microservice
 * Micro service to online bakery
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.mikrobrama.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * OrderBreadRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-23T15:31:47.012026+01:00[Europe/Warsaw]")
public class OrderBreadRequest {
  @JsonProperty("person")
  private Person person = null;

  @JsonProperty("payment")
  private PaymentCard payment = null;

  @JsonProperty("bread")
  private Bread bread = null;

  @JsonProperty("deliveryPlace")
  private DeliveryPlace deliveryPlace = null;

  public OrderBreadRequest person(Person person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  public Person getPerson() {
    return person;
  }

  public void setPerson(Person person) {
    this.person = person;
  }

  public OrderBreadRequest payment(PaymentCard payment) {
    this.payment = payment;
    return this;
  }

   /**
   * Get payment
   * @return payment
  **/
  public PaymentCard getPayment() {
    return payment;
  }

  public void setPayment(PaymentCard payment) {
    this.payment = payment;
  }

  public OrderBreadRequest bread(Bread bread) {
    this.bread = bread;
    return this;
  }

   /**
   * Get bread
   * @return bread
  **/
  public Bread getBread() {
    return bread;
  }

  public void setBread(Bread bread) {
    this.bread = bread;
  }

  public OrderBreadRequest deliveryPlace(DeliveryPlace deliveryPlace) {
    this.deliveryPlace = deliveryPlace;
    return this;
  }

   /**
   * Get deliveryPlace
   * @return deliveryPlace
  **/
  public DeliveryPlace getDeliveryPlace() {
    return deliveryPlace;
  }

  public void setDeliveryPlace(DeliveryPlace deliveryPlace) {
    this.deliveryPlace = deliveryPlace;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderBreadRequest orderBreadRequest = (OrderBreadRequest) o;
    return Objects.equals(this.person, orderBreadRequest.person) &&
        Objects.equals(this.payment, orderBreadRequest.payment) &&
        Objects.equals(this.bread, orderBreadRequest.bread) &&
        Objects.equals(this.deliveryPlace, orderBreadRequest.deliveryPlace);
  }

  @Override
  public int hashCode() {
    return Objects.hash(person, payment, bread, deliveryPlace);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderBreadRequest {\n");
    
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    payment: ").append(toIndentedString(payment)).append("\n");
    sb.append("    bread: ").append(toIndentedString(bread)).append("\n");
    sb.append("    deliveryPlace: ").append(toIndentedString(deliveryPlace)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
