/*
 * online bakery microservice
 * Micro service to online bakery
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.mikrobrama.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;

/**
 * OrderInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-23T15:31:47.012026+01:00[Europe/Warsaw]")
public class OrderInfo {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("cost")
  private BigDecimal cost = null;

  @JsonProperty("person")
  private Person person = null;

  @JsonProperty("payment")
  private PaymentCard payment = null;

  @JsonProperty("deliveryPlace")
  private DeliveryPlace deliveryPlace = null;

  public OrderInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public OrderInfo cost(BigDecimal cost) {
    this.cost = cost;
    return this;
  }

   /**
   * Get cost
   * @return cost
  **/
  public BigDecimal getCost() {
    return cost;
  }

  public void setCost(BigDecimal cost) {
    this.cost = cost;
  }

  public OrderInfo person(Person person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  public Person getPerson() {
    return person;
  }

  public void setPerson(Person person) {
    this.person = person;
  }

  public OrderInfo payment(PaymentCard payment) {
    this.payment = payment;
    return this;
  }

   /**
   * Get payment
   * @return payment
  **/
  public PaymentCard getPayment() {
    return payment;
  }

  public void setPayment(PaymentCard payment) {
    this.payment = payment;
  }

  public OrderInfo deliveryPlace(DeliveryPlace deliveryPlace) {
    this.deliveryPlace = deliveryPlace;
    return this;
  }

   /**
   * Get deliveryPlace
   * @return deliveryPlace
  **/
  public DeliveryPlace getDeliveryPlace() {
    return deliveryPlace;
  }

  public void setDeliveryPlace(DeliveryPlace deliveryPlace) {
    this.deliveryPlace = deliveryPlace;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderInfo orderInfo = (OrderInfo) o;
    return Objects.equals(this.id, orderInfo.id) &&
        Objects.equals(this.cost, orderInfo.cost) &&
        Objects.equals(this.person, orderInfo.person) &&
        Objects.equals(this.payment, orderInfo.payment) &&
        Objects.equals(this.deliveryPlace, orderInfo.deliveryPlace);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, cost, person, payment, deliveryPlace);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    payment: ").append(toIndentedString(payment)).append("\n");
    sb.append("    deliveryPlace: ").append(toIndentedString(deliveryPlace)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
