//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.15 at 09:42:57 PM CET 
//


package org.bp.cake;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="person" type="{http://www.bp.org/types}Person"/&gt;
 *         &lt;element name="deliveryPlace" type="{http://www.bp.org/types}DeliveryPlace"/&gt;
 *         &lt;element name="cake" type="{http://www.bp.org/types}Cake"/&gt;
 *         &lt;element name="payment" type="{http://www.bp.org/types}PaymentCard"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "person",
    "deliveryPlace",
    "cake",
    "payment"
})
@XmlRootElement(name = "orderCakeRequest", namespace = "http://www.bp.org")
public class OrderCakeRequest {

    @XmlElement(namespace = "http://www.bp.org", required = true)
    protected Person person;
    @XmlElement(namespace = "http://www.bp.org", required = true)
    protected DeliveryPlace deliveryPlace;
    @XmlElement(namespace = "http://www.bp.org", required = true)
    protected Cake cake;
    @XmlElement(namespace = "http://www.bp.org", required = true)
    protected PaymentCard payment;

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setPerson(Person value) {
        this.person = value;
    }

    /**
     * Gets the value of the deliveryPlace property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryPlace }
     *     
     */
    public DeliveryPlace getDeliveryPlace() {
        return deliveryPlace;
    }

    /**
     * Sets the value of the deliveryPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryPlace }
     *     
     */
    public void setDeliveryPlace(DeliveryPlace value) {
        this.deliveryPlace = value;
    }

    /**
     * Gets the value of the cake property.
     * 
     * @return
     *     possible object is
     *     {@link Cake }
     *     
     */
    public Cake getCake() {
        return cake;
    }

    /**
     * Sets the value of the cake property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cake }
     *     
     */
    public void setCake(Cake value) {
        this.cake = value;
    }

    /**
     * Gets the value of the payment property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentCard }
     *     
     */
    public PaymentCard getPayment() {
        return payment;
    }

    /**
     * Sets the value of the payment property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentCard }
     *     
     */
    public void setPayment(PaymentCard value) {
        this.payment = value;
    }

}
